siteTitle="Notes"
baseColor = "#db594c"
linkPrefix = "/notes"
notePages = [
  '/notes/scripts-injection/',
  '/notes/component-playground/',
  '/notes/utility-snippets/',
  '/notes/static-site-generator/',
]
